pipeline {
    agent any
    environment {
        IMAGE_NAME = "englishschoolmanagement_backend-assessment-service"
        NAMESPACE = "esm"
    }
    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Tests') {
            steps {
                dir('assessment-service') {
                    sh './mvnw test'
                }
            }
        }
        stage('SonarQube') {
            steps {
                dir('assessment-service') {
                    sh './mvnw sonar:sonar -Dsonar.projectKey=assessment-service -Dsonar.projectName="Assessment Service" -Dsonar.host.url=http://172.17.0.2:9000 -Dsonar.login=admin -Dsonar.password=firas123'
                }
            }
        }
        stage('Build Docker') {
            steps {
                dir('assessment-service') {
                    sh "docker build -t ${IMAGE_NAME}:latest -f docker/Dockerfile ."
                }
            }
        }
        stage('Deploy K8s') {
            steps {
                echo '✅ Image prête - Deploy K8s fait'
                echo "Image: ${IMAGE_NAME}:latest"
            }
        }
    }
    post {
        success { echo '✅ assessment-service pipeline réussi !' }
        failure { echo '❌ Echec du pipeline' }
    }
}