pipeline {
    agent any
    environment {
        IMAGE_NAME = "englishschoolmanagement_backend-assessment-service"
        NAMESPACE = "esm"
    }
    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Tests') {
            steps {
                dir('assessment-service') {
                    sh './mvnw test'
                }
            }
        }
        stage('Build Docker') {
            steps {
                dir('assessment-service') {
                    sh "docker build -t ${IMAGE_NAME}:latest -f docker/Dockerfile ."
                }
            }
        }
        stage('Deploy K8s') {
            steps {
                sh "kubectl set image deployment/assessment-service assessment-service=${IMAGE_NAME}:latest -n esm --server=https://192.168.49.2:8443 --certificate-authority=/var/lib/jenkins/ca.crt --client-certificate=/var/lib/jenkins/client.crt --client-key=/var/lib/jenkins/client.key"
            }
        }
    }
    post {
        success { echo 'assessment-service pipeline reussi !' }
        failure { echo 'Echec du pipeline' }
    }
}