apiVersion: v1
kind: Service
metadata:
  name: esmauthms-svc
  namespace: esm
spec:
  selector:
    app: esmauthms
  type: NodePort
  ports:
    - port: 1999
      targetPort: 1999
      nodePort: 31999
