# ⚠  Base64-encode your real values:  echo -n 'value' | base64
apiVersion: v1
kind: Secret
metadata:
  name: messaging-secret
  namespace: esm
type: Opaque
data:
  db-username: ZXNt                                              # esm
  db-password: ZXNtc2VjcmV0                                     # esmsecret
  mailjet-api-key: YjI0MjAzOGQ5NTY3ZmUwODAxY2M1NDk1YjIxN2FlYTE=  # b242038d...
  mailjet-secret-key: OTYzMjAwNjBjYmNkN2YxY2UzMGE1OWViYzRhNTUxZjE=
