apiVersion: v1
kind: Service
metadata:
  name: resources-service-svc
  namespace: esm
  labels:
    app: resources-service
spec:
  selector:
    app: resources-service
  type: NodePort
  ports:
    - port: 8096
      targetPort: 8096
      nodePort: 30096
