# DOCKER PROFILE - PostgreSQL persistent database (data survives restart)
spring.datasource.url=jdbc:postgresql://postgres-courses:5432/courses_db
spring.datasource.username=esm
spring.datasource.password=esm_secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=false

# Run without Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
