# ============================================================
# APPLICATION
# ============================================================
spring.application.name=notification-service
server.port=${SERVER_PORT:2001}
server.servlet.context-path=/api

# ============================================================
# EUREKA
# ============================================================
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}
eureka.client.register-with-eureka=${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
eureka.client.fetch-registry=${EUREKA_CLIENT_FETCH_REGISTRY:true}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${EUREKA_INSTANCE_INSTANCE_ID:notification-service:2001}

# ============================================================
# DATABASE
# ============================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/email_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:esm}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:esmsecret}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ============================================================
# MAILJET CONFIG
# ============================================================
mailjet.api-key=${MAILJET_API_KEY:b242038d9567fe0801cc5495b217aea1}
mailjet.secret-key=${MAILJET_SECRET_KEY:96320060cbcd7f1ce30a59ebc4a551f1}
mailjet.sender-email=${MAILJET_SENDER_EMAIL:blink@akrem.dev}
mailjet.sender-name=${MAILJET_SENDER_NAME:ESM Platform}

# ============================================================
# SWAGGER
# ============================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ============================================================
# LOGGING
# ============================================================
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n