pipeline {
    agent any

    environment {
        IMAGE_NAME = "englishschoolmanagement_backend-resources-service"
        NAMESPACE = "esm"
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Tests') {
            steps {
                echo 'Tests skipped - no mvnw in resources-service'
            }
        }
        stage('Build Docker') {
            steps {
                dir('resources-service') {
                    sh "docker build -t ${IMAGE_NAME}:latest -f Dockerfile ."
                }
            }
        }
        stage('Deploy K8s') {
            steps {
                sh "minikube image load ${IMAGE_NAME}:latest"
                sh "kubectl rollout restart deployment/resources-service -n ${NAMESPACE}"
            }
        }
    }
    post {
        success { echo '✅ resources-service déployé !' }
        failure { echo '❌ Échec du pipeline' }
    }
}
