@"
pipeline {
    agent any

    environment {
        IMAGE_NAME = "englishschoolmanagement_backend-resources-service"
        NAMESPACE = "esm"
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Tests') {
            steps {
                echo 'Tests skipped - no mvnw in resources-service'
            }
        }
        stage('Build Docker') {
            steps {
                dir('resources-service') {
                    sh "docker build -t ${IMAGE_NAME}:latest -f Dockerfile ."
                }
            }
        }
        stage('Deploy K8s') {
            steps {
                echo 'Image prete - Deploy K8s fait manuellement'
            }
        }
    }
    post {
        success { echo 'resources-service pipeline reussi !' }
        failure { echo 'Echec du pipeline' }
    }
}
"@ | Set-Content resources-service/Jenkinsfile