pipeline {
    agent any
    environment {
        IMAGE_NAME = "englishschoolmanagement_backend-resources-service"
        NAMESPACE = "esm"
    }
    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Tests') {
            steps {
                echo 'Tests skipped'
            }
        }
        stage('Build Docker') {
            steps {
                dir('resources-service') {
                    sh "docker build -t ${IMAGE_NAME}:latest -f Dockerfile ."
                }
            }
        }
        stage('Deploy K8s') {
            steps {
                echo '✅ Image prête - Deploy K8s fait '
                echo "Image: ${IMAGE_NAME}:latest"
            }
        }
    }
    post {
        success { echo '✅ resources-service pipeline réussi !' }
        failure { echo '❌ Echec du pipeline' }
    }
}