apiVersion: v1
kind: Secret
metadata:
  name: assessment-service-secret
  namespace: esm
type: Opaque
data:
  db-username: cm9vdA==        # root
  db-password: cm9vdA==        # root
  jwt-secret: bXlzdXBlcnNlY3VyZWp3dHNlY3JldGtleW15c3VwZXJzZWN1cmVqd3RzZWNyZXRrZXk=
